INSERT INTO `nihilframework`.`ac_auth_item_children` (`parent`, `child`) VALUES 

('administrator', 'ecomAttributesIndex'),
('administrator', 'ecomAttributesView'),
('administrator', 'ecomAttributesDetails'),
('administrator', 'ecomAttributesCreate'),
('administrator', 'ecomAttributesUpdate'),
('administrator', 'ecomAttributesDelete'),
('administrator', 'ecomAttributesList'),

('administrator', 'ecomAttributeGroupsIndex'),
('administrator', 'ecomAttributeGroupsView'),
('administrator', 'ecomAttributeGroupsDetails'),
('administrator', 'ecomAttributeGroupsCreate'),
('administrator', 'ecomAttributeGroupsUpdate'),
('administrator', 'ecomAttributeGroupsDelete'),
('administrator', 'ecomAttributeGroupsList'),

('administrator', 'ecomAuthnetTransactionsIndex'),
('administrator', 'ecomAuthnetTransactionsView'),
('administrator', 'ecomAuthnetTransactionsDetails'),
('administrator', 'ecomAuthnetTransactionsCreate'),
('administrator', 'ecomAuthnetTransactionsUpdate'),
('administrator', 'ecomAuthnetTransactionsDelete'),
('administrator', 'ecomAuthnetTransactionsList'),

('administrator', 'ecomCataloguesIndex'),
('administrator', 'ecomCataloguesView'),
('administrator', 'ecomCataloguesDetails'),
('administrator', 'ecomCataloguesCreate'),
('administrator', 'ecomCataloguesUpdate'),
('administrator', 'ecomCataloguesDelete'),
('administrator', 'ecomCataloguesList'),

('administrator', 'ecomCustomersIndex'),
('administrator', 'ecomCustomersView'),
('administrator', 'ecomCustomersDetails'),
('administrator', 'ecomCustomersCreate'),
('administrator', 'ecomCustomersUpdate'),
('administrator', 'ecomCustomersDelete'),
('administrator', 'ecomCustomersList'),

('administrator', 'ecomDepartmentsIndex'),
('administrator', 'ecomDepartmentsView'),
('administrator', 'ecomDepartmentsDetails'),
('administrator', 'ecomDepartmentsCreate'),
('administrator', 'ecomDepartmentsUpdate'),
('administrator', 'ecomDepartmentsDelete'),
('administrator', 'ecomDepartmentsList'),

('administrator', 'ecomInvoiceItemsIndex'),
('administrator', 'ecomInvoiceItemsView'),
('administrator', 'ecomInvoiceItemsDetails'),
('administrator', 'ecomInvoiceItemsCreate'),
('administrator', 'ecomInvoiceItemsUpdate'),
('administrator', 'ecomInvoiceItemsDelete'),
('administrator', 'ecomInvoiceItemsList'),

('administrator', 'ecomInvoiceStatusesIndex'),
('administrator', 'ecomInvoiceStatusesView'),
('administrator', 'ecomInvoiceStatusesDetails'),
('administrator', 'ecomInvoiceStatusesCreate'),
('administrator', 'ecomInvoiceStatusesUpdate'),
('administrator', 'ecomInvoiceStatusesDelete'),
('administrator', 'ecomInvoiceStatusesList'),

('administrator', 'ecomOrdersIndex'),
('administrator', 'ecomOrdersView'),
('administrator', 'ecomOrdersDetails'),
('administrator', 'ecomOrdersCreate'),
('administrator', 'ecomOrdersUpdate'),
('administrator', 'ecomOrdersDelete'),
('administrator', 'ecomOrdersList'),

('administrator', 'ecomOrderItemsIndex'),
('administrator', 'ecomOrderItemsView'),
('administrator', 'ecomOrderItemsDetails'),
('administrator', 'ecomOrderItemsCreate'),
('administrator', 'ecomOrderItemsUpdate'),
('administrator', 'ecomOrderItemsDelete'),
('administrator', 'ecomOrderItemsList'),

('administrator', 'ecomOrderStatusesIndex'),
('administrator', 'ecomOrderStatusesView'),
('administrator', 'ecomOrderStatusesDetails'),
('administrator', 'ecomOrderStatusesCreate'),
('administrator', 'ecomOrderStatusesUpdate'),
('administrator', 'ecomOrderStatusesDelete'),
('administrator', 'ecomOrderStatusesList'),

('administrator', 'ecomPaymentsIndex'),
('administrator', 'ecomPaymentsView'),
('administrator', 'ecomPaymentsDetails'),
('administrator', 'ecomPaymentsCreate'),
('administrator', 'ecomPaymentsUpdate'),
('administrator', 'ecomPaymentsDelete'),
('administrator', 'ecomPaymentsList'),

('administrator', 'ecomPaymentMethodsIndex'),
('administrator', 'ecomPaymentMethodsView'),
('administrator', 'ecomPaymentMethodsDetails'),
('administrator', 'ecomPaymentMethodsCreate'),
('administrator', 'ecomPaymentMethodsUpdate'),
('administrator', 'ecomPaymentMethodsDelete'),
('administrator', 'ecomPaymentMethodsList'),

('administrator', 'ecomPaymentTypesIndex'),
('administrator', 'ecomPaymentTypesView'),
('administrator', 'ecomPaymentTypesDetails'),
('administrator', 'ecomPaymentTypesCreate'),
('administrator', 'ecomPaymentTypesUpdate'),
('administrator', 'ecomPaymentTypesDelete'),
('administrator', 'ecomPaymentTypesList'),

('guest', 'ecomProductsIndex'),
('guest', 'ecomProductsView'),
('administrator', 'ecomProductsDetails'),
('administrator', 'ecomProductsCreate'),
('administrator', 'ecomProductsUpdate'),
('administrator', 'ecomProductsDelete'),
('administrator', 'ecomProductsList'),

('administrator', 'ecomProductAttributesIndex'),
('administrator', 'ecomProductAttributesView'),
('administrator', 'ecomProductAttributesDetails'),
('administrator', 'ecomProductAttributesCreate'),
('administrator', 'ecomProductAttributesUpdate'),
('administrator', 'ecomProductAttributesDelete'),
('administrator', 'ecomProductAttributesList'),

('administrator', 'ecomShippingAddressesIndex'),
('administrator', 'ecomShippingAddressesView'),
('administrator', 'ecomShippingAddressesDetails'),
('administrator', 'ecomShippingAddressesCreate'),
('administrator', 'ecomShippingAddressesUpdate'),
('administrator', 'ecomShippingAddressesDelete'),
('administrator', 'ecomShippingAddressesList');